base: 'https://derzahnarzt.de/'
baseVariants:
  -
    base: 'https://derzahnarzt.ddev.site/'
    condition: 'getenv("IS_DDEV_PROJECT") == "true"'
dependencies:
  - typo3/form
  - typo3/seo-sitemap
  - typo3/redirects
  - aistea/aisteacorp
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    locale: de_DE
    navigationTitle: Deutsch
    flag: de
    hreflang: 'de-DE'
    websiteTitle: 'Der Zahnarzt'
rootPageId: 1
websiteTitle: 'Der Zahnarzt'
